Repository NOAA-GFDL/fre-cli, pull requests merged in 2025-08, with the labels that each got.

#565 Adjust how the version is specified
  .cspell.json
  .cspell/ok-unknown-words.txt
  .github/workflows/spell_check.yml
  .gitignore
  README.md
  docs/Makefile
  docs/conf.py
  fre/__init__.py
  pyproject.toml
  setup.py
Labels: documentation, new functioning, tricky, clean up

#511 docs: attempting header documentation for split-netcdf
  .cspell/ok-unknown-words.txt
  docs/contributing_to_doc.rst
  fre/app/helpers.py
  fre/app/tests/test_helpers.py
  fre/pp/split_netcdf_script.py
  fre/pp/tests/test_split_netcdf.py
  fre/pp/tests/test_split_netcdf_regex.py
  fre/tests/test_files/ascii_files/split_netcdf/atmos_daily.tile3/none_ts_varlist/am5_components_varlist.yml
  fre/tests/test_files/ascii_files/split_netcdf/atmos_daily.tile3/some_ts_varlist/am5_components_varlist.yml
Labels: documentation

#591 remove uncovered `__name__=="__main__"` entrypoints
  fre/analysis/freanalysis.py
  fre/app/freapp.py
  fre/app/generate_time_averages/generate_time_averages.py
  fre/app/regrid_xy/regrid_xy.py
  fre/catalog/frecatalog.py
  fre/check/frecheck.py
  fre/check/frecheckexample.py
  fre/cmor/frecmor.py
  fre/fre.py
  fre/list_/frelist.py
  fre/make/fremake.py
  fre/make/run_fremake_script.py
  fre/pp/checkout_script.py
  fre/pp/configure_script_yaml.py
  fre/pp/frepp.py
  fre/pp/histval_script.py
  fre/pp/nccheck_script.py
  fre/pp/ppval_script.py
  fre/pp/run_script.py
  fre/pp/split_netcdf_script.py
  fre/pp/status_script.py
  fre/pp/trigger_script.py
  fre/pp/validate_script.py
  fre/pp/wrapper_script.py
  fre/run/frerun.py
  fre/run/frerunexample.py
  fre/yamltools/freyamltools.py
Labels: clean up

#562 doc: fre pp documentation task 3
  docs/tools.rst
  docs/tools/pp.rst
  fre/pp/README.md
  fre/pp/checkout_script.py
  fre/pp/configure_script_yaml.py
  fre/pp/frepp.py
  fre/pp/install_script.py
  fre/pp/run_script.py
  fre/pp/status_script.py
  fre/pp/trigger_script.py
  fre/pp/wrapper_script.py
Labels: documentation

#536 Regrid_xy rewrite and pytests
  fre/app/regrid_xy/regrid_xy.py
  fre/app/regrid_xy/tests/generate_files.py
  fre/app/regrid_xy/tests/test_fre_regrid_xy_functions.py
  fre/app/regrid_xy/tests/test_regrid_xy.py
  fre/app/regrid_xy/tests/write_gridfiles.py
Labels: new functioning, tricky, clean up

#594 docs: `fre/pp/__init__.py`
  fre/pp/__init__.py
Labels: documentation
