Repository NOAA-GFDL/fre-cli, pull requests merged in 2025-07, with the labels that each got.

#530 doc: `readthedocs` workflow improvement
  .github/workflows/create_test_conda_env.yml
  .readthedocs.yaml
  docs/api.rst
  docs/conf.py
  docs/contributing_to_doc.rst
  docs/for-developers.rst
  docs/for-maintainers.rst
  docs/index.rst
  docs/setup.rst
  setup.py
Labels: documentation, new functioning, clean up, priority: HIGH

#529 Fix "cylc scan --name [experiment] not found"
  fre/pp/run_script.py
Labels: bug

#537 docs: deprecate `gh-pages` and fix badges
  .github/workflows/create_test_conda_env.yml
  README.md
  coveragerc
  docs/badges.rst
  docs/contributing_to_doc.rst
  docs/index.rst
  fre/list_/tests/__init__.py
  meta.yaml
  pytest.ini
Labels: bug, documentation, priority: HIGH

#463 Add remap-pp-components as fre-cli tool
  coveragerc
  fre/app/freapp.py
  fre/app/helpers.py
  fre/app/remap_pp_components/README.md
  fre/app/remap_pp_components/__init__.py
  fre/app/remap_pp_components/remap_pp_components.py
  fre/app/remap_pp_components/tests/__init__.py
  fre/app/remap_pp_components/tests/test-data/atmos_scalar.198001-198412.co2mass.cdl
  fre/app/remap_pp_components/tests/test-data/atmos_static_scalar.bk.cdl
  fre/app/remap_pp_components/tests/test-data/yaml_ex.yaml
  fre/app/remap_pp_components/tests/test_remap_pp_components.py
  fre/app/tests/test_helpers.py
  fre/tests/test_fre_app_cli.py
Labels: new functioning, tricky
